name: covid19
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.2
  flutter_launcher_icons: ^0.7.4
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.4+3
  google_sign_in: ^4.4.4
  firebase_auth: ^0.16.0
  firebase_database: ^3.1.3
  flutter_datetime_picker: ^1.3.8
  location_platform_interface: ^1.0.0
  # dynamic_tabs: ^1.0.2+3
  firebase_storage: ^3.1.5
  image_picker: ^0.6.5+2
  intl: ^0.16.1
  dropdown_formfield: ^0.1.2
  google_maps_flutter: ^0.5.26+4
  font_awesome_flutter: ^8.8.1
  flutter_email_sender: ^3.0.1
  cupertino_icons: ^0.1.2
  location: ^3.0.2
  url_launcher: ^5.4.5
  geoflutterfire: ^2.1.0
  rxdart: ^0.23.1
  # geofencing: ^0.0.1
dependency_overrides:
  image: ^2.1.12
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
